version: '3'

services:
  app2:
    build:
      context: ./src/app2
    ports:
      - "5001:5001"
    networks:
      - app-network
    volumes:
      - ./models/tinyllama-1b:/app/models/tinyllama-1b
      - ./offload:/app/offload
    environment:
      - HF_HOME=/app/models
      - TRANSFORMERS_OFFLINE=1
      - TOKENIZERS_PARALLELISM=false
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 1g
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    dns:
      - 8.8.8.8
      - 8.8.4.4

  app1:
    build:
      context: ./src/app1
    ports:
      - "5002:5002"
    networks:
      - app-network
    volumes:
      - ./models/tinyllama-1b:/app/models/tinyllama-1b
      - ./offload:/app/offload
    environment:
      - HF_HOME=/app/models
      - TRANSFORMERS_OFFLINE=1
      - TOKENIZERS_PARALLELISM=false
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 1g
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge
