version: '3'

services:
  app1:
    build:
      context: ./src/app1
      platforms:
        - linux/amd64
    ports:
      - "5002:5002"
    environment:
      - HF_HOME=/app/models
      - TRANSFORMERS_OFFLINE=0
      - TOKENIZERS_PARALLELISM=false
      - MODEL_SERVER_URL=https://3529-2001-f40-90e-62cd-ace4-d62e-323f-6852.ngrok-free.app
      - NODE2_URL=https://your-app2-url-from-phala.network  # You'll replace this after deploying app2
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    dns:
      - 8.8.8.8
      - 8.8.4.4 